### ISSUE TITLE
where to customize? 

### ISSUE THREAD

**Issue by filipgoc** [n3dst4/atom-wrap-with-anything#2]
This may be self evident, but I can't find it. 
I can see the readme that says. 

> You can customise this list in the settings.

But I do not see any settings. Other than the readme. 

![image](https://cloud.githubusercontent.com/assets/16858474/25352637/06686fb0-292d-11e7-8cbb-d8ef8627b730.png)

Thanks!

**Comment by n3dst4** [comment]
Hey! Really sorry I never saw this and left you hanging for 7 months. On the off-chance you still give a damn :) the settings **should be** right below where you took that screenshot:

![image](https://user-images.githubusercontent.com/280206/33138975-d260d356-cfa3-11e7-93e1-28df8f6e84e0.png)

**Comment by n3dst4** [comment]
On a side-note, it turns out I'm literally not watching most of my own repositories, wtf?

**Comment by filipgoc** [comment]
:-) 

Similarly, I have now realized what the problem was:

### You need to RESTART Atom for the 'settings' to appear.

(While you do not need to restart for the plugin to work with default settings.)

Be well and thanks for your time and all!
